name: pokedex
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.OTF
        - asset: assets/fonts/SF-Pro-Display-Bold.OTF
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Medium.OTF
          weight: 500

  generate: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/pokeball.png
  color_dark: "#121212"
  image_dark: assets/images/pokeball.png

  android_12:
    image: assets/images/pokeball.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/pokeball.png
    icon_background_color_dark: "#121212"

  web: false